version: '3.5'

services:
  dev_db_local:
    container_name: dev_db
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/